# fly.toml app configuration file generated for tiendarhinomexico on 2023-06-05T12:46:14-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tiendarhinomexico"
primary_region = "gdl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
